pulse_analytics:
  outputs:
    trino:
      type: trino
      host: "{{ env_var('PULSE_ANALYTICS_TRINO_HOST') }}"
      port: "{{ env_var('PULSE_ANALYTICS_TRINO_PORT') | int }}"
      user: "{{ env_var('PULSE_ANALYTICS_TRINO_USER') }}"
      database: "{{ env_var('PULSE_ANALYTICS_TARGET_CATALOG') }}"
      schema: "{{ env_var('PULSE_ANALYTICS_TARGET_SCHEMA') }}"
      method: ldap
      password: "{{ env_var('PULSE_ANALYTICS_TRINO_PASSWORD') }}"
      http_scheme: https
      cert: false

    duckdb:
      type: duckdb
      path: "{{ env_var('PULSE_ANALYTICS_DUCKDB_PATH') }}"  # The catalog is the file name w/o extension
      schema: "{{ env_var('PULSE_ANALYTICS_TARGET_SCHEMA') }}"
